### PR TITLE
feat: use os.availableConcurrency

### LINKED ISSUE #497: Make Max Threads default to `os.availableParallelism()` https://nodejs.org/api/os.html#osavailableparallelism
I think we could default it to `os.availableParallelism()` https://nodejs.org/api/os.html#osavailableparallelism

_Originally posted by @RafaelGSS in https://github.com/piscinajs/piscina/pull/487#discussion_r1467637405_

### PR DESCRIPTION
**Pull request by metcoder95**
- **feat: use available parallelism instead of cpu count**
- **fix: smaller adjustments**

### CODE REVIEW

**Review by RafaelGSS — APPROVED** [review]

**Comment by cjinhuo** [comment]
hello excuse me, os.availableConcurrency added in: v19.4.0, v18.14.0. But I saw README indicate it for Node.js 16.x and higher. And I had installed ^4.4.0 in node16.x enviroment. Today I re-deployed and found it was broken in here.

**Comment by cjinhuo** [comment]
Can I pull a request to fix this issue

**Comment by cjinhuo** [comment]
> Can I pull a request to fix this issue

please check this [PR](https://github.com/piscinajs/piscina/pull/570)

**Comment by metcoder95** [comment]
Workaround has been done, please verify `4.5.1`

**Pull request merged**
