### PR TITLE
feat: use @napi-rs/nice to support Windows

### PR DESCRIPTION
**Pull request by Brooooooklyn**
- `@napi-rs/nice` is easier to install on CI
- `@napi-rs/nice` supports Windows

### CODE REVIEW

**Review by metcoder95 — COMMENTED** [review]
Nice! This looks great, thanks for the contribution.

CI seems broken tho

**Comment by Brooooooklyn** [comment]
@metcoder95 thanks, fixed

**Comment by metcoder95** [comment]
Now Windows does not seems to be happy

**Comment by Brooooooklyn** [comment]
Tests now passed on my Windows and Linux computer 🥇

**Comment by metcoder95** [comment]
Let's adjust the test to distinguish between linux and windows scenarios 👍

**Review by metcoder95 — APPROVED** [review]

**Pull request merged**
