### PR TITLE
fix: transferrable not being transferred

### PR DESCRIPTION
**Pull request by Deivu**
I noticed that returning a `Transferable objects` from a worker doesn't get the object transferred, instead it's being cloned.

To verify this, I created my own Implementation of Transferrable
```js
class Shared {
    constructor({ ok, time, data } = {}) {
        this.ok = ok;
        this.time = time;
        this.data = data;
    }

    get [Piscina.transferableSymbol]() {
        return [this.data];
    }

    get [Piscina.valueSymbol]() {
        return { ok: this.ok, time: this.time, data: this.data };
    }

    make() {
        return Piscina.move(this);
    }
}

module.exports = Shared;
```
Then logged my buffer's byteLength intially, then after 1 second.

Without this fix, the byteLength didn't change, which signifies the buffer was not transferred
image
With the fix, the byteLength did change, which signifies the buffer was transferred
image

### CODE REVIEW

**Comment by addaleax** [comment]
@Deivu Is this something that you could add a test for?

**Comment by Deivu** [comment]
@addaleax  Took me some time to get the test working, but I did manage to add a test for it

**Comment by arielszn** [comment]
Hey, we tried using the `Piscina.move()` feature for transferring a big object we need to deserialise on a worker thread, and then again a `Piscina.move()` from the worker thread to transfer back the deserialised object to the main thread, but this is not impacting on memory usage and latency as we were expecting for this change, we think it's not behaving as expected because of the issue that @Deivu is solving here.
Do you plan to merge this soon?

**Review by jasnell — APPROVED** [review]

**Comment by jasnell** [comment]
Hmm looks like we've got a CI problem. I'll have to investigate that this weekend

**Comment by sogame** [comment]
Hi @jasnell, I'm also interested in this fix for my project, any luck with the CI issues? 😬

**Comment by arielszn** [comment]
> Hey, we tried using the `Piscina.move()` feature for transferring a big object we need to deserialise on a worker thread, and then again a `Piscina.move()` from the worker thread to transfer back the deserialised object to the main thread, but this is not impacting on memory usage and latency as we were expecting for this change, we think it's not behaving as expected because of the issue that @Deivu is solving here. Do you plan to merge this soon?

Hey, any news over here :) ?

**Comment by nicholas-l** [comment]
Hey all, I have identified the issue with CI and have created a quick fix: https://github.com/piscinajs/piscina/pull/161

**Comment by sogame** [comment]
Hi @Deivu, now that the CI issue has been solved (in https://github.com/piscinajs/piscina/pull/161), could you update your branch with `master`, so the new build is triggered? 😇

**Comment by sogame** [comment]
Hi @jasnell would it be possible to get this fix merged (and even release a new version of `piscina` with it), please? 😇 
Really looking forward to test my project with this improvement 🚀

**Comment by jasnell** [comment]
Running CI now, let's see where that lands first!

**Comment by jasnell** [comment]
merged! I'll look at cutting a new release tomorrow afternoon

**Pull request merged**
