### PR TITLE
Add communication from worker to main thread

### LINKED ISSUE #212: Workers to main thread communication
I need to add a way to send messages from workers to main thread:

The only possibility I see right now with Piscina, is to send a messagePort when running a task and use it to communicate (Or use a broadcastChannel but only for node 17+).

In my case, I want to use a single messagePort per worker, set at startup of the worker and use it when initializing inside the worker and before running tasks... But there is no currently easy way to add a messagePort per worker at startup built in Piscina...

I wonder if it would be possible to use the already existing built in messages ports of Piscina to add this feature ?

Something like this:

Adding a new kind of message that the worker can send:
```js
export interface GenericMessage {
  data: any;
}
```

Use it to send messages from worker at any stage:
```js
let message : GenericMessage;
parentPort.postMessage(message);
```

And handle such messages at pool level to expose it:
```js
worker.on('message', (message : GenericMessage) => {
  publicInterface.emit('message', message.data);
}
```

Do this make sense ?

### PR DESCRIPTION
**Pull request by Elyahou**
Fix: https://github.com/piscinajs/piscina/issues/212

### CODE REVIEW

**Review by jasnell — APPROVED** [review]
LGTM but I'd like to get @addaleax's opinion also

**Comment by Elyahou** [comment]
@jasnell @addaleax Any news ?

**Comment by alolis** [comment]
@Elyahou, can you please provide instructions on how did you add "current" branch of piscina to your project in order to use your merged PR?

I am mostly interested with the steps AFTER the `npm/yarn add https://github.com/piscinajs/piscina.git#current` part ;)

**Comment by metcoder95** [comment]
You can take a look at npm official docs [here](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#github-urls).
Recommend you stay tuned for possible upgrades/merges against the main branch as is possible that unexpected changes can break your app between installations 🙂

**Pull request merged**
