### PR TITLE
feat: expose task interface

### PR DESCRIPTION
**Pull request by metcoder95**
- **chore: split worker pool and task queue implementation**
- **refactor: remove leftovers**

### CODE REVIEW

**Comment by metcoder95** [comment]
I'm trying to decouple the Task Queue and Worker Pool implementation so they can grow independently, mostly aiming for enable the work for  #536 and do it progressively; I'd target the new balancer work directly to `next` as safe bet

**Review by RafaelGSS — COMMENTED** [review]
Is it semver-major?

**Comment by metcoder95** [comment]
Don't think so, wasn't exported before, but if we want to be careful, we can do so

**Comment by metcoder95** [comment]
Just wanted to verify if is true that we did not expose these types, and indeed we don't.
The only form to have access to them was through

```ts
import type { Task } from 'piscina/dist/types';
```

Which is not officially supported, instead to access the same types they can do:
```ts
import type { PiscinaTask } from 'piscina';
```

**Comment by metcoder95** [comment]
I'll be merging the PR, if there's extra feedback, feel free to add it here and I'll address it in further PR

**Pull request merged**
